### ISSUE TITLE
Support for Fahrenheit 

### ISSUE THREAD

**Issue by drewharbin** [universam1/iSpindel#142]
Not really an issue, but will we see an option to change the temp reading to Fahrenheit in future releases?  I have my ispindel connected to my Craftbeerpi which is set to F and the temp is sent as C but denoted as F on my dashboard.

Thanks,
Drew

**Comment by FernandoGarcia** [comment]
Hi!
Are you using compiled version?
Best regards.

**Comment by drewharbin** [comment]
Just using latest firmware release.

**Comment by drewharbin** [comment]
Awesome! Got it going!  The above overloaded the function but once I figured out how to compile I was able to make the edits to convert to Fahrenheit.  Thank you so much for the guidance,

**Comment by universam1** [comment]
A proper implementation is always welcome as a PR!

**Comment by FernandoGarcia** [comment]
I can make it selectable via code but not via web page for now.

**Comment by universam1** [comment]
Actually the request of this feature is somewhat questionable since the iSpindel is not the system that is presenting a user interface thus coping with the users formatting. 
It provides a common interface of communication that the backend is expecting. Now if we introduce optional formats we break a standard!

In this case craftbeerpi is to support several temperatur formats to display, which it does! So we could even state that it is a big or missing implementation in CBP and a issue has to be open for that. 
I am not against Fahrenheit to support but I am worried about breaking a standard

**Comment by FernandoGarcia** [comment]
Well, you are the admin of this branch so if do you want add this option let me know and will try a PR.
