### ISSUE TITLE
Option to turn the esp's blue led off 

### ISSUE THREAD

**Issue by ErikdBr** [universam1/iSpindel#273]
Because I didn't want to risk ruining my esp I left all the leds intact despite it is recommended to solder them off.
So is it possible to built in an option in the config where you can opt to turn the blue led off to save power while in a fermenter. I found some code on the web that will turn it off by default but I don't know how and where to put it in the code, so if someone could implement that, that would be awsome!

//**ESP onboard LED: Blaue LED auschalten
Direkt beim Start wird die interne LED definiert und anschließend abgeschaltet, indem man sie auf „HIGH“ setzt. Dadurch wird die sehr hell leuchtende, blaue LED auf der Oberseite des ESP- oder NodeMCU Board ausgeschaltet:
**//

void setup() {
  pinMode(LED_BUILTIN, OUTPUT); // LED als Output definieren
  digitalWrite(LED_BUILTIN, HIGH); // Ausschalten
}

**Comment by universam1** [comment]
It is not possible because it is the data pin for IIC of the accelerometer.
However it only flashes during data transmission which is the wake up time, so it uses basically no power. 

However the led on the accelerometer is static power on an cannot be turned of via software so this one needs to be desoldered
