### ISSUE TITLE
reading in water changes

### ISSUE THREAD

**Issue by arjepsen** [universam1/iSpindel#288]
Hey.
I'm trying to calibrate my ispindel, and I've put it in water outputting to ubidots every 20 seconds.
I had to leave it there for a while due to family activites - no problem, right.
But now when I'm looking at the graph in ubidots, it starts out averaging around 74.42.
However, currently it's averaging around 74.54
I think the temperature has gone up 0.6 from 23.1 degrees celcius to 23.7
Is that what changes the tilt here??

**Comment by ErikdBr** [comment]
Yep that's it. Other than that, your tilt is way to high, in water it should be around 20 (+/-5).
You'll need to add some weight at the bottom of your iSpinde like a nut and washers until you reach the desired tilt.
![image](https://user-images.githubusercontent.com/48140503/61173137-4a7b1f00-a58f-11e9-9f12-ac998d1dec7a.png)

**Comment by arjepsen** [comment]
hmm.. I read somewhere that it should be around 25 degrees. I attached a few pieces of metal  to the bottom, and measured the tilt to around 20 degrees from the vertical plane. This gave me the tilt reading of  74.54.

**Comment by ErikdBr** [comment]
@arjepsen a reading of 74.54 in plain water or in a sugar solution?

**Comment by arjepsen** [comment]
plain water

**Comment by ErikdBr** [comment]
I am not getting how you measured the 20 degrees. Calibrating is: go in the iSpindel config menu and go to the maintenance menu. Lay the iSpindel flat on a flat level surface and click calibrate. After that is ready it should give you a tilt of about 90 degrees.
Then with the iSpindel in operating mode put it in plain water and add weight until you get a tilt of about 20 degrees, plus or minus 5 degrees.
So how you measured a tilt of 74 in plain water is a riddle to me.

**Comment by arjepsen** [comment]
I might be influenced by working as a math teacher....
I used a degree-measuring-tool (not sure what it's called in english).
According to the ispindel docs, you have to add weights untill the inclination is 25 degrees from vertical.
I added a bit more weight, so now my inclination is about 35 degrees to vertical... and the tilt measures 60.82

**Comment by ErikdBr** [comment]
> I used a degree-measuring-tool (not sure what it's called in english).
> According to the ispindel docs, you have to add weights untill the inclination is 25 degrees from vertical.

Yes 25 degrees( + or - 5 ) **tilt** in plain water measured by the iSpindel itself, not by hand with a measuring tool.
If your tilt is 70-ish in plain water it will float upside down in your wort, lol.

**Comment by arjepsen** [comment]
> If your tilt is 70-ish in plain water it will float upside down in your wort, lol.
mmm not really.

**Comment by ErikdBr** [comment]
I hope this will clearify it. The drawing represents an iSpindel in plain water.
![20190714_113647](https://user-images.githubusercontent.com/48140503/61181848-e65a6880-a62b-11e9-9aad-0da5d4444e10.jpg)

**Comment by ErikdBr** [comment]
The angle of 20 in water represents sg 1.000. When you put it in wort, the angle increases to let's say 60 degrees which could be let's say sg 1.068. When fermentation progresses the angle of the iSpindel decreases because the density of the wort decreases ergo has less resistance ergo will sink a little deeper in the wort.

**Comment by ErikdBr** [comment]
A few pics to clearify it more, yesterday afternoon I pitched and got this reading
![20190714_115446](https://user-images.githubusercontent.com/48140503/61182077-a0eb6a80-a62e-11e9-9b1b-ff0ea1e3f5a3.jpg)

Just now I got this:
![20190714_115513](https://user-images.githubusercontent.com/48140503/61182082-c1b3c000-a62e-11e9-9d9c-00838bb92d36.jpg)

Compare the two angles. The angle decreases as fermentation progresses.
Don't mind the temperature it is completely accurate and on purpose because I used a special yeast called Hornindal Kveik which ferments at high temperatures but that is a hole different story.
![2019-6-14-3](https://user-images.githubusercontent.com/48140503/61182114-41418f00-a62f-11e9-97f2-e82fe902c844.png)

**Comment by ErikdBr** [comment]
> > If your tilt is 70-ish in plain water it will float upside down in your wort, lol.
> 
> mmm not really.

Sorry about that.

**Comment by arjepsen** [comment]
Thanks for your descriptions. I guess I got confused, since it seems the need for weights etc. is only mentioned in the FAQ, not in the general guidelines on the ispindel website. 
Anyways, managed to get it to 25 degrees in clean water. Thanks for your help! :-)
