### ISSUE TITLE
Date /time stamp

### ISSUE THREAD

**Issue by mcmellow** [universam1/iSpindel#317]
Using Firmware 6.20 and configured the iSpindel to MQTT.  On my Raspberry Pi runs a MQTT Broker and it works great. Just of the shelve. 
I love to have a date-time stamp in the MQTT message. Is this possible?

**Comment by universam1** [comment]
The iSpindel does not have date-time information available, and it will not have since this would be a very expensive, time consuming process for each and every wake-up.
However, the MQTT server does track and have this meta information with the message anyway, you actually should already get this information back when subscribing.

**Comment by mcmellow** [comment]
OK, Thanks for the clear answer.
