### ISSUE TITLE
Can ZigBee be an alternative to Wifi?

### ISSUE THREAD

**Issue by 7wells** [universam1/iSpindel#472]
Hello!

Would it make sense (and is it feasible) to use a ZigBee module as an alternative to Wifi? I am not sure whether ZigBee would have advantages over Wifi, e.g. better transmission through fluids, steel etc., so maybe my proposal/question does not make sense. If it does, there are ZigBee gateways without clouds, e.g. [there](https://phoscon.de/de/raspbee2) - see also [there](https://github.com/dresden-elektronik).

Happy brewing! 👍

**Comment by thormj** [comment]
Possibly... I mean the commercial one is done via Bluetooth... but you'd need to have a Wemos ZigBee module and the code and...
I was thinking about converting back to Bluetooth, but that would be an even more open invitation for lawyers.

BLE (and probably ZigBee) can be higher radio power (special transmit modes to prevent rf pollution and such), but I don't think you're allowed to go much bigger on WiFi.  Nothing likes water.  Few things like steel (but WiFi, bluetooth, and zigbee kinda work; you can go ~20 feet through a fridge but not much more).

Slightly lighter and longer (so the antenna is sticking out of the brew more) will help more than anything else.  But it's also harder than most things because you'll need new plastics.
