### ISSUE TITLE
Cant calibrate battery voltage

### ISSUE THREAD

**Issue by Seedler1981** [universam1/iSpindel#474]
Sorry if this is the wrong place for this.  I cant get battery voltage to read.  It just displays 5.34v.  when I connect a 230k resistor to A0 the resistance falls to below 200k.  No matter what size of resister i add i always get a reading of 5.34v.  

Thanks

**Comment by JochenV1976** [comment]
I had the same problem. When using the calibration formula, the calibration factor seems to high (>230).

I changed it to 230, and now the reading is +/- OK.
I programmed the iSpindel to send it's data every minute, and it has been working now for almost 4 days. Battery voltage hasn't dropped, not even with 0.01V? I will check with a multimeter, because that looks strange to me.

**Comment by ErikdBr** [comment]
I use a Schottkey BAT43 diode instead of the resistor. Report every 15 minutes results in a voltage drop of 0.015V every 24 hours, below 3.2V it start to report every hour automaticaly and at 2.5V it shuts itself down. The lower the voltage gets, the more the voltage is dropping every 24 hours at last, just above 2.5V, it dropped like 0.03 every 24 hours.
